#!/usr/bin/python3
# 6-raise_exception_msg.py

def raise_exception_msg(message=""):
    try:
        return (value)
    except NameError:
        print(message)
